### ISSUE TITLE
Setup forms for setting up transects and plots

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/dunes-app#5]
1)      A list of predefined Dune sites on the website.
2)      An Add Transect button for each site.
3)      Takes you to a form for adding a transect, with tools for drawing the line. The transect will have the parent site set to the Dune site.
4)      Add option to assign habitat to transect (habitats list as used for the smpAttr:1499)
5)      A list of saved transects with Edit and Add Plot links.
6)      Add plot takes you to a plot addition form, where the parent site is defaulted to the chosen transect.
7)      A Filterable list of plots so you can access edit links for existing plots.

**Comment by kazlauskis** [comment]
Note, the habitats will be per transect section/point. There should be a way to attach an image to a point/section too.

**Comment by johnvanbreda** [comment]
1. Should the edit forms and report pages use the same OS + Google Satellite combined layers as iRecord?
2. When editing a transect, is there any need for a grid reference input control, or shall I just hide this and take the centroid from the drawn line?
3. When editing a transect, is there any need for a grid reference input control, or shall I just hide this and take the centroid from the drawn line?
4. If we are allowing grid reference input for plots or transects, do we want to allow additional systems to be supported, e.g. lat long?

**Comment by DavidRoy** [comment]
1. No Google Satellite (at least initially) as we'd need to setup a payment structure for that.  OpenLayers only
2. No need for grid reference input control
3. ditto :-).  Or did you mean plots?  Input control for plots would be needed as these may be setup using GPS unit on site
4. Support for OSGB (no need for Ireland), plus lat/long

**Comment by johnvanbreda** [comment]
Thanks - sorry, yes, I meant plots for 3.
Are plots simple points, or do we need to allow for transect section lines?

**Comment by DavidRoy** [comment]
@kazlauskis or @LaurenceJonesES can confirm but I think the plots are either points or 2m square.  But I think they can both be handled as points (either centroid or bottom-left corner).

**Comment by LaurenceJonesES** [comment]
Will try and clarify structure needed (& hopefully it agrees with suggestions so far). Using A,B etc. to avoid confusion with numbers used above.
A) Transect/group is a higher level aggregation containing grouped locations within a site. Sometimes these will form a transect (with pre-set Start and End, and other points added later by the app user), sometimes it will be a group of pre-set locations which are found in one part of the site, sometimes it may be a dummy group for all locations on a site (to keep a consistent structure in the app/website).
B) Actual Transects will need a defined Start and End point to be set up by the site manager. Currently, no other point locations will be pre-set along a transect, but see following:
C) Other point locations will need fixed locations setting up by the site manager & linking to a transect/group
D) One type of point location - Fixed point photographs - may be scattered across the site, or may be along a transect. Key aspect is to be able to link/assign individual points to a particular transect or group
E) Another type of point location - Vegetation quadrat - may also be scattered around, or may be along a transect. Again, need to be able to link/assign to a particular transect or group
F) Quadrats are 2x2 m. They will need an attribute assigned for Habitat type (note it doesn't make sense to link the attribute of Habitat type to a transect or group). Each quadrat will have a grid reference assigned. For the website and the app, that's all we need to know (but for users, sometimes the grid ref will mark a post, sometimes the quadrat itself) 
G) Dipwells are the other main pre-set point location, as above need to be able to link to a group
H) Disturbance locations are recorded by users ad-hoc, so don't need to be set up beforehand, but the database needs to be able to store them from the app
I) Let me know if its useful to attach the latest version of the manual.

**Comment by DavidRoy** [comment]
Thanks Laurence.  For my own understanding and from the website perspective.
B. So all transects are straight lines only?
C. point locations can be linked to the straight-line transects even if not spatially on the transect line?
F. For 2x2m quadrats, what is the grid reference (1m - 10 digit gridreference) - the centroid or one of the corners
D & E & G. For 'link/assign to a group'.  Does that option need to be available via the website - i.e. site managers assign the group when setting up locations?  How does the grouping link to/differ from transect 'groups'

**Comment by LaurenceJonesES** [comment]
We haven't discussed this explicitly, but this is the structure that has emerged-
A) Transect and Group are the higher level aggregation (parent), each having daughter locations assigned. But they have a different structure so probably need to be set up differently. My suggestion is as follows:
B) Transects are only straight lines, with a specified start and end. These are set up by the site manager on the website. Daughter locations will be added by the user as they move along the transect, using the app (and so linked to the parent transect within the app)
C, D, E & G) Group is the parent for Quadrats, Fixed point photos or Dipwells. Groups are created with a name by the site manager, but are not georeferenced. Also differing from the way transects are set up is that Quadrats, Fixed point photos and Dipwells ARE georeferenced, with those locations set up by the site manager on the website  
C, D, E, F & G) Grid references will be given to 1 m, but it would be useful to have the capability to store location with a DGPS grid reference for 1 cm accuracy (i.e. Easting and Northing given separately, to 3 decimal places)

**Comment by DavidRoy** [comment]
Thanks.  I'll leave @johnvanbreda to ask for any clarification for the website functionality

**Comment by johnvanbreda** [comment]
I've reformatted the notes above as a list of requirement statements for the website:
* Sites are preloaded into the system from the provided sheet.
* A site manager can access an edit page for a site.
* The site edit page allows the site manager to define a list of transects at the site. The 
  transect has a name, start GPS coordinate and end GPS coordinate and are linked as children of
  the site.
* The site edit page allows the site manager to define a list of "groups" at the site. The group
  has a name and no spatial information. For simplicity, the group may be stored internally as a
  child location of the site and could share that site's centroid grid ref.
* The site manager can access an edit page for transects and groups.
* The edit page for a group allows the site manager to add a list of points (=child 
  locations) which will be one of the following:
  * Fixed point photo
  * Vegetation quadrat (2x2m) with a habitat type attribute
  * Dipwells

Please can you confirm the above requirements are correct @LaurenceJonesES? Also I have the following questions:

* Please confirm that the following lists of attributes for each type of data are correct:
  * Transect:
    * Name
    * Parent site
    * Start coordinate
    * End coordinate
  * Group:
    * Name
    * Parent site
  * Fixed point photo:
    * Name (if we can't name it, store the grid ref in the name field?)
    * Grid reference (maybe Easting/Northing)
  * Quadrat:
    * Name (if we can't name it, store the grid ref in the name field?)
    * Grid reference (maybe Easting/Northing)
    * Habitat type
  Dipwell:
    * Name (if we can't name it, store the grid ref in the name field?)
    * Grid reference (maybe Easting/Northing)
* Transects will initially be defined as a straight line. Your notes say that the app user can add 
  other points later - does this mean the app user can redraw the transect line in any shape? But
  this can't be done in the website? Or shall we keep the transect line a straight line and just
  store the precise points of the transect which may not be exactly on the line?
* Just to confirm - the site manager will add fixed point locations within a group, but the website
  won't be used to add fixed point locations to a transect? These will only be done within the app?
* Habitat type can only be assigned for vegetation quadrats, not other fixed points?
* The app user can add a disturbance location - I think it makes sense to store this as a sample 
  rather than a location (so it is transient with a date rather than a permanent defined location)?
* When the app user adds points to a transect, are these fixed points, or just transient recording 
  points? If they are fixed points, is there a type we can allocate to them (like quadrats, fixed 
  photo points, or dipwell). Or are they just simply child points of the transect?
* Easting/Northings - if just an X,Y coordinate we can support this using the system notation 
  27700. Is that what you mean by DPSG?

**Comment by kazlauskis** [comment]
Speaking from the app's perspective it is unclear to me why we need groups at this stage. Sorry, if I have missed something important from your discussion above 🙂 In the app we are simply using the word 'Group' for a transect in the Plant Quadrat Recording activity but essentially these can be defined as transects. I wonder if a simpler set up would suffice:  Site -> Transect -> Point (of different types). 

We will not be drawing lines between points in the app yet, so everything could be simple points nested within a transect. For the Zonation & Profile activities, transects will have 2 fixed points only (start/end). For other surveys, transects would have multiple fixed points.

**Transect**:
* Name
* Parent site
* Grid reference 

**Point** - Fixed point photo activity:
* Grid reference
* Image

**Point** - Dipwell activity:
* Grid reference
* Image

**Point** - Quadrat activity:
* Grid reference
* Image
* Habitat type [smpAttr:1499]

**Point** - Dune Zonation & Profile activities:
* Grid reference
* Image
* Type: [start, end] (would be good to restrict to only 2 points in the transect)

**Comment by LaurenceJonesES** [comment]
I don't have a preference for how this is implemented, as long as the functionality that I outlined can be achieved. It may be simplest to define the two different sets of parent (i.e. Transect, Group) if that's the easiest way to set them up. It strikes me they are quite different in set up, but share the common characteristic of having child locations attached, but in different ways.

**Comment by DavidRoy** [comment]
In terms of the database, the structure will be the same as a three level hierarchy of site-transect/group-plot/point

@johnvanbreda is the simplest way to handle the requirement from the website is to have two 'location_types' at level 2
- 'transect' or 'quadrat group'

and two 'location_types' at level 3
- 'point' or 'quadrat'

Also, is it worth checking with @sacrevert (and Andy vB) for how they are handling quadrat (releve) data in NPMS and PlantPortal projects

**Comment by LaurenceJonesES** [comment]
If we go with two types at Level 2, then I suggest calling 'transect' or 'group' (since they won't all be quadrats, & need to include dipwells & fixed point photos.

Apologies for naive question, but is the need for different types dictated by requirements for setting them up on the website, or does it need to take account of the type of data & attributes that will be recorded as well ?

I wonder if a call is the quickest way to make progress here. I'm available all afternoon, would be useful to have John, myself and at least one of David or Karolis.

**Comment by kazlauskis** [comment]
I'm free for a call as well.

**Comment by LaurenceJonesES** [comment]
I've set up a zoom link, sent by email, but copied here. Its an open slot, so join if you can.  I've removed zoom link from here as this site is open
@johnvanbreda are you free for a quick call on this?

**Comment by DavidRoy** [comment]
@johnvanbreda can you let me know when you expect to have the transect/plot setup forms available so I can inform the testers

**Comment by johnvanbreda** [comment]
After discussion with @LaurenceJonesES and @kazlauskis we've determined the following data structure:
1. A list of dune sites in the locations table, each holding just a name and centroid grid reference, with the location type set to "Dune site". These have been pre-loaded into the system from a CSV file.
2. Site managers can add a transect. These are stored in the locations table with the following attributes:
  * name
  * parent site
  * centroid grid reference (British National Grid or decimal GPS lat long)
  * geometry - a single straight line from which we can determine the start and end point data. Note that it is important to be clear which end is the start and which is the end.
  * bearing - will be calculated if possible
  * a photo for the start of the transect (auto-resized so < 500kb)
  * a photo for the end of the transect (auto-resized so < 500kb)
3. Site managers can add fixed points. These are stored in the locations table with the following attributes:
  * name
  * parent site
  * centroid grid reference (British National Grid or decimal GPS lat long)
  * x, y and z coordinates as custom attributes where a very precise location needs to be stored.
  * location type - either fixed point photo, dipwell, or quadrat
  * habitat type (custom attribute) - only for quadrats.
  * group - a custom attribute that allows fixed points to be grouped for any arbitrary reason, e.g. North or South.
  * a single photo (auto-resized so < 500kb)
4. When the app is used to add data for a transect, there is a parent sample which has the transect's ID in the samples.location_id field, plus the transect's centroid in the entered_sref field. Each point along the transect is recorded in the samples table as a sub-sample, with the same location_id and a precise British National Grid Ref or GPS lat long for the point along the transect. There is no need to create locations for these points as they are not persistent locations and might change between visits.
5. When the app is used to add data for fixed points, there is a parent sample which has the site's ID in the samples.location_id field, plus the site's centroid in the entered_sref field. Each sub-sample has a fixed-point location's ID and centroid sref in the data stored. 
6. When the app is used to capture a disturbance point, a sample is created with the exact location in the entered_sref and the location_id set to the Dune site.

Please can everyone check the above makes sense.

@DavidRoy as the requirements are still evolving it's hard to know. I'd done a first stab at the site setup forms yesterday but it will need some revision.

**Comment by DavidRoy** [comment]
Thanks - a productive discussion.  This makes sense to me.  Keep me posted on timescales so I can give testers some warning of when their input is needed

**Comment by kazlauskis** [comment]
> When the app is used to add a disturbance point, is this part of a survey, or a one off? Presumably it would be a sample linked to the dune site?

Yes, that's one off and we will attach the site location id to the sample we submit.

**Comment by LaurenceJonesES** [comment]
All makes sense to me, although I have a question on new transect structure.
2. Transect geometry as a line. Does this allow start and end to be pre-defined ?  For most transects it will matter which point is defined as the start (i.e. can't be automated), and will affect the bearing given to the user (see next point)
-We mentioned transect bearings, I assume that doesn't need to be highlighted in the structure outlined above ?

**Comment by johnvanbreda** [comment]
I've updated https://github.com/NERC-CEH/dunes-app/issues/5#issuecomment-662509025 to reflect the comments above so it represents the latest info.

**Comment by johnvanbreda** [comment]
@DavidRoy I will hopefully have this all ready by the end of today.

**Comment by johnvanbreda** [comment]
@DavidRoy this is now done. Users who are going to test it need to be added to the Site manager role. There is a little test data on the Ainsdale Hills site.

**Comment by kazlauskis** [comment]
I've just opened this up and created a point. Looks good to me. Will the `group` dropdown provide existing groups for the site or is it essentially a text field where you have to retype your group (I only got 'undefined' as options now)?

Edit: also, what reports do you think I should use to pull the data out?

**Comment by DavidRoy** [comment]
Thanks John.  Works well from my quick test. I'll ask some site managers to test.

**Comment by johnvanbreda** [comment]
@kazlauskis yes, the text field for groups should offer existing groups as suggestions - I've just fixed that.

What fields do you need in the reports?

**Comment by kazlauskis** [comment]
Ideally, I would like to call a report passing the site param (site location id?) as a filter. This would then return me all the fixed points with:
* Type (Fixed photo, dipwell etc)
* Location
* Image
* Habitat type

Also for the transects which could be the same report or a different one:
* Centroid grid reference
* Shape
* Images
* Bearing

**Comment by johnvanbreda** [comment]
@kazlauskis is WKT OK for the transect shape and which projection (e.g. WGS 84, or OSGB 1936, or Web Mercator)?

**Comment by johnvanbreda** [comment]
@kazlauskis there is a first draft of the report at projects/dunescapes/locations_list_for_app.xml. It combines both fixed points and transects into a single report but can be filtered by setting the location_type_id parameter to one of:
17807	"Quadrat"
17806	"Dipwell"
17805	"Fixed point photo"
777		"Transect"

Pass parent_id to filter by site. The media column is a JSON array of image paths.

**Comment by kazlauskis** [comment]
Sorry, I think I will also need the `group` attribute returned to be able to group the points/quadrats together.

**Comment by kazlauskis** [comment]
The current projection you use is fine, I can transform the geoms to GeoJSON in the client.

**Comment by johnvanbreda** [comment]
I've added a Group column @kazlauskis.

**Comment by DavidRoy** [comment]
@johnvanbreda feedback on location setup forms:

The process worked fine except for some strange reason on T5 the webpage wouldn’t allow me to enter -5.148130 as a longitude for transect end. I checked a few times and then tried -5.148131 instead, which it accepted.

**Comment by johnvanbreda** [comment]
The value -5.148130 would be accepted as -5.14813 - the combination of a negative with a zero at the end caused the validation code to fire when it shouldn't. I've committed a fix which will be deployed in the next few days.

**Comment by DavidRoy** [comment]
@johnvanbreda has the fix of zero at end of decimals been implemented?  Still getting reports of this bug

**Comment by johnvanbreda** [comment]
Sorry @DavidRoy there were 2 problems in the validation of negative floats and I'd only spotted the first. Now definitely fixed.
